name: northguard
description: "Northguard Flutter project."

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.10.4

dependencies:
  auto_hyphenating_text: ^0.3.1
  auto_size_text: ^3.0.0
  biometric_signature: ^9.0.1
  built_collection: ^5.1.1
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.3.0
  dio: ^5.9.0
  encrypt: ^5.0.3
  equatable: ^2.0.7
  file_picker: ^10.3.8
  flutter:
    sdk: flutter
  flutter_autofill_service:
    path: flutter_autofill_service
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  fluttertoast: ^9.0.0
  flutter_pdfview: ^1.4.3
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.3
  flutter_webview_plugin:
    path: flutter_webview_plugin-master
  font_awesome_flutter: ^10.12.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_fonts: ^6.3.3
  http: ^1.6.0
  image: ^4.7.2
  image_picker: ^1.2.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  local_auth: ^3.0.0
  location: ^8.0.1
  mime: ^2.0.0
  mobile_scanner: ^7.1.4
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  privacy_screen:
    path: privacy_screen-master
  qr_flutter: ^4.1.0
  rxdart: ^0.28.0
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0

dev_dependencies:
  build_runner: ^2.10.4
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  lints: ^6.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Italic.ttf
          style: italic

  assets:
    - assets/
    - assets/user_default.png
    - js/lib/other/prototypes.js
    - js/lib/srp6a/thinbus-srp6a-sha256-versioned.js
    - js/lib/srp6a/thinbus-srp-config.js
    - js/lib/elliptic.min.js
    - js/lib/elliptic.min.js
    - js/lib/forge.min.js
    - js/lib/pcrypt.js
    - js/lib/pcrypt.config.js
    - js/lib/
    - js/_.js
    - .env

analyzer:
  errors:
    invalid_annotation_target: ignore

